"""
opengxp.org
Copyright (C) 2019  Henrik Baran

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

# app imports
from urp.decorators import auth_required

# rest imports
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.reverse import reverse


@api_view(['GET'])
@auth_required(initial_password_check=False)
def private_root_view(request):
    root = {'base': {'csrftoken': {'url': {'abs': reverse('get_csrf_token', request=request),
                                           'rel': 'csrftoken'}},
                     'logout': {'url': {'abs': reverse('logout-view', request=request),
                                        'rel': 'logout'}},
                     'meta': {'url': {'abs': '',
                                      'rel': 'meta/<str:subject>'}},
            'logout_auto': {'url': {'abs': reverse('logout-auto-view', request=request),
                                    'rel': 'logout_auto'}}},
            'user': {'profile': {'url': {'abs': reverse('profile-list', request=request),
                                         'rel': 'user/profile'}},
                     'inbox': {'url': {'abs': reverse('inbox-list', request=request),
                                       'rel': 'user/inbox'}},
                     'set_timezone': {'url': {'abs': reverse('set-timezone-view', request=request),
                                      'rel': 'user/set_timezone'}},
                     'profile_questions': {'url': {'abs': reverse('user-profile-list', request=request),
                                           'rel': 'user/profile_questions'}},
                     'change_password': {'url': {'abs': reverse('user-change-password-view', request=request),
                                                 'rel': 'user/change_password'}},
                     'change_questions': {'url': {'abs': reverse('user-change-questions-view', request=request),
                                                  'rel': 'user/change_questions'}}},
            'navigation': {'admin_ngxp': {'title': 'Non-GxP Administration',
                                          'subjects': {'ldap': {'title': 'LDAP',
                                                                'url': {'abs': reverse('ldap-list', request=request),
                                                                        'rel': 'admin/ldap'},
                                                                'log': {'abs': reverse('ldap-log-list',
                                                                                       request=request),
                                                                        'rel': 'logs/ldap'},
                                                                'post': True,
                                                                'patch': True,
                                                                'delete': True,
                                                                'version': False,
                                                                'status': None},
                                                       'email': {'title': 'Email',
                                                                 'url': {'abs': reverse('email-list', request=request),
                                                                         'rel': 'admin/email'},
                                                                 'log': {'abs': reverse('email-log-list',
                                                                                        request=request),
                                                                         'rel': 'logs/email'},
                                                                 'post': True,
                                                                 'patch': True,
                                                                 'delete': True,
                                                                 'version': False,
                                                                 'status': None},
                                                       'settings': {'title': 'Settings',
                                                                    'url': {'abs': reverse('settings-list',
                                                                                           request=request),
                                                                            'rel': 'admin/settings'},
                                                                    'log': {'abs': reverse('settings-log-list',
                                                                                           request=request),
                                                                            'rel': 'logs/settings'},
                                                                    'post': False,
                                                                    'patch': True,
                                                                    'delete': False,
                                                                    'version': False,
                                                                    'status': None},
                                                       'passwords': {'title': 'Passwords',
                                                                     'url': {'abs': reverse('users-password-list',
                                                                                            request=request),
                                                                             'rel': 'admin/passwords'},
                                                                     'log': {'abs': reverse('users-log-list',
                                                                                            request=request),
                                                                             'rel': 'logs/users'},
                                                                     'post': False,
                                                                     'patch': True,
                                                                     'delete': False,
                                                                     'version': False,
                                                                     'status': None},
                                                       'tags': {'title': 'Tags',
                                                                'url': {'abs': reverse('tags-list', request=request),
                                                                        'rel': 'admin/tags'},
                                                                'log': {'abs': reverse('tags-log-list',
                                                                                       request=request),
                                                                        'rel': 'logs/tags'},
                                                                'post': True,
                                                                'patch': True,
                                                                'delete': True,
                                                                'version': False,
                                                                'status': None},
                                                       'spaces': {'title': 'Spaces',
                                                                  'url': {'abs': reverse('spaces-list',
                                                                                         request=request),
                                                                          'rel': 'admin/spaces'},
                                                                  'log': {'abs': reverse('spaces-log-list',
                                                                                         request=request),
                                                                          'rel': 'logs/spaces'},
                                                                  'post': True,
                                                                  'patch': True,
                                                                  'delete': True,
                                                                  'version': False,
                                                                  'status': None}}},
                           'admin_gxp': {'title': 'GxP Administration',
                                         'subjects': {'roles': {'title': 'Roles',
                                                                'url': {'abs': reverse('roles-list', request=request),
                                                                        'rel': 'admin/roles'},
                                                                'log': {'abs': reverse('roles-log-list',
                                                                                       request=request),
                                                                        'rel': 'logs/roles'},
                                                                'post': True,
                                                                'patch': True,
                                                                'delete': True,
                                                                'version': True,
                                                                'status': 'md'},
                                                      'users': {'title': 'Users',
                                                                'url': {'abs': reverse('users-list', request=request),
                                                                        'rel': 'admin/users'},
                                                                'log': {'abs': reverse('users-log-list',
                                                                                       request=request),
                                                                        'rel': 'logs/users'},
                                                                'post': True,
                                                                'patch': True,
                                                                'delete': True,
                                                                'version': True,
                                                                'status': 'md'},
                                                      'sod': {'title': 'SoD',
                                                              'url': {'abs': reverse('sod-list', request=request),
                                                                      'rel': 'admin/sod'},
                                                              'log': {'abs': reverse('sod-log-list', request=request),
                                                                      'rel': 'logs/sod'},
                                                              'post': True,
                                                              'patch': True,
                                                              'delete': True,
                                                              'version': True,
                                                              'status': 'md'}}},
                           'md_gxp': {'title': 'GxP Master Data',
                                      'subjects': {'lists': {'title': 'Lists',
                                                             'url': {'abs': reverse('lists-list', request=request),
                                                                     'rel': 'md/lists'},
                                                             'log': {'abs': reverse('lists-log-list', request=request),
                                                                     'rel': 'logs/lists'},
                                                             'post': True,
                                                             'patch': True,
                                                             'delete': True,
                                                             'version': True,
                                                             'status': 'md'},
                                                   'workflows': {'title': 'Workflows',
                                                                 'url': {'abs': reverse('workflows-list',
                                                                                        request=request),
                                                                         'rel': 'md/workflows'},
                                                                 'log': {'abs': reverse('workflows-log-list',
                                                                                        request=request),
                                                                         'rel': 'logs/workflows'},
                                                                 'post': True,
                                                                 'patch': True,
                                                                 'delete': True,
                                                                 'version': True,
                                                                 'status': 'md'},
                                                   'forms': {'title': 'Forms',
                                                             'url': {'abs': reverse('forms-list', request=request),
                                                                     'rel': 'md/forms'},
                                                             'log': {'abs': reverse('forms-log-list', request=request),
                                                                     'rel': 'forms/lists'},
                                                             'post': True,
                                                             'patch': True,
                                                             'delete': True,
                                                             'version': True,
                                                             'status': 'md'}}},
                           'rtd': {'title': 'Runtime Data',
                                   'subjects': {'execution': {'title': 'Execution',
                                                              'url': {'abs': reverse('execution-list', request=request),
                                                                      'rel': 'rtd/execution'},
                                                              'log': {'abs': reverse('execution-log-list',
                                                                                     request=request),
                                                                      'rel': 'logs/execution'},
                                                              'log-values': {'abs': reverse('execution-values-log-list',
                                                                                            request=request),
                                                                             'rel': 'logs/execution_values'},
                                                              'post': True,
                                                              'patch': False,
                                                              'delete': True,
                                                              'version': False,
                                                              'status': 'rtd'}}},
                           'logs': {'title': 'Logs',
                                    'subjects': {'central': {'title': 'Central',
                                                             'url': {'abs': reverse('central-log-list',
                                                                                    request=request),
                                                                     'rel': 'logs/central'}},
                                                 'access': {'title': 'Access',
                                                            'url': {'abs': reverse('access-log-list', request=request),
                                                                    'rel': 'logs/access'}},
                                                 'signatures': {'title': 'Signatures',
                                                                'url': {'abs': reverse('signatures-log-list',
                                                                                       request=request),
                                                                        'rel': 'logs/signatures'}},
                                                 'roles': {'title': 'Roles',
                                                           'url': {'abs': reverse('roles-log-list', request=request),
                                                                   'rel': 'logs/roles'}},
                                                 'ldap': {'title': 'LDAP',
                                                          'url': {'abs': reverse('ldap-log-list', request=request),
                                                                  'rel': 'logs/ldap'}},
                                                 'email': {'title': 'Email',
                                                           'url': {'abs': reverse('email-log-list', request=request),
                                                                   'rel': 'logs/email'}},
                                                 'users': {'title': 'Users',
                                                           'url': {'abs': reverse('users-log-list', request=request),
                                                                   'rel': 'logs/users'}},
                                                 'tags': {'title': 'Tags',
                                                          'url': {'abs': reverse('tags-log-list', request=request),
                                                                  'rel': 'logs/tags'}},
                                                 'spaces': {'title': 'Spaces',
                                                            'url': {'abs': reverse('spaces-log-list', request=request),
                                                                    'rel': 'logs/spaces'}},
                                                 'sod': {'title': 'SoD',
                                                         'url': {'abs': reverse('sod-log-list', request=request),
                                                                 'rel': 'logs/sod'}},
                                                 'settings': {'title': 'Settings',
                                                              'url': {'abs': reverse('settings-log-list',
                                                                                     request=request),
                                                                      'rel': 'logs/settings'}},
                                                 'profile': {'title': 'Profile',
                                                             'url': {'abs': reverse('profile-log-list',
                                                                                    request=request),
                                                                      'rel': 'logs/profile'}},
                                                 'lists': {'title': 'Lists',
                                                           'url': {'abs': reverse('lists-log-list', request=request),
                                                                   'rel': 'logs/lists'}},
                                                 'workflows': {'title': 'Workflows',
                                                               'url': {'abs': reverse('workflows-log-list',
                                                                                      request=request),
                                                                       'rel': 'logs/workflows'}},
                                                 # FO-241: adapted model key correctly for meta
                                                 'workflowssteps': {'title': 'Workflows Steps',
                                                                    'url': {'abs': reverse(
                                                                            'workflows-steps-log-list',
                                                                            request=request),
                                                                            'rel': 'logs/workflows_steps'}},
                                                 'forms': {'title': 'Forms',
                                                           'url': {'abs': reverse('forms-log-list',
                                                                                  request=request),
                                                                   'rel': 'logs/forms'}},
                                                 # FO-241: adapted model key correctly for meta
                                                 'formssections': {'title': 'Forms Sections',
                                                                   'url': {'abs': reverse(
                                                                       'forms-sections-log-list',
                                                                       request=request),
                                                                       'rel': 'logs/forms_sections'}},
                                                 # FO-241: adapted model key correctly for meta
                                                 'formstextfields': {'title': 'Forms Text Fields',
                                                                     'url': {'abs': reverse(
                                                                         'forms-text-fields-log-list',
                                                                         request=request),
                                                                         'rel': 'logs/forms_text_fields'}},
                                                 # FO-241: adapted model key correctly for meta
                                                 'formsboolfields': {'title': 'Forms Bool Fields',
                                                                     'url': {'abs': reverse(
                                                                         'forms-bool-fields-log-list',
                                                                         request=request),
                                                                         'rel': 'logs/forms_bool_fields'}},
                                                 'execution': {'title': 'Execution',
                                                               'url': {'abs': reverse('execution-log-list',
                                                                                      request=request),
                                                                       'rel': 'logs/execution'}},
                                                 # FO-241: adapted model key correctly for meta
                                                 'executionfields': {'title': 'Execution Values',
                                                                     'url': {'abs': reverse(
                                                                         'execution-values-log-list',
                                                                         request=request),
                                                                         'rel': 'logs/execution_values'}}
                                                 }}}}

    return Response(root)
